services:
  db_user:
    image: postgres
    restart: always
    volumes:
      - ./modules/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    networks:
      - default

  user:
    build: ./
    ports:
      - 30005:30005
    depends_on:
      - db_user
    networks:
      - skynet
      - default

networks:
  skynet:
    external: true
  default:
    external: false
